version: '3'
services:

  fastapi:
    build: .
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done &&
      alembic revision --autogenerate -m "create table" &&
      alembic upgrade head &&
      uvicorn app.main:app --reload --host 0.0.0.0'
    volumes:
      - ./app:/backend/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"