version: '3'
services:

  fastapi:
    build: .
    command: >
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done &&
      uvicorn app.main:app --reload --host 0.0.0.0'
    volumes:
      - ./app:/backend/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
